### ISSUE TITLE
Sessions without data create extra record on every request.

### ISSUE THREAD

**Issue by alextech** [zendframework/zend-expressive-session-ext#22]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-session-ext/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-session-ext/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Using sessions which have no values stored in them. Typically applicable to guest vs. logged in user.

### Expected results

Session record to be created only once per connection for all further requests on that connection, or not at all, unless deliberately reset by application needs.

### Actual results

Every request generates a new session. Depending on storage method this causes one of:

- If use file system as storage it becomes overloaded. New files are created at huge pace even in a light dev environment at hundreds per week.
- If using database as storage, in hosts like Heroku that charge in tiers of number of rows used, can eat through data plans very quickly.
- if using memory cache (redis, memcache), overload unreasonably quickly.

It brings a question of session file cleanup at way too early in the development process, or in places where it would not be considered at all, like low traffic intranet tools.

**Comment by geerteltink** [comment]
As I said on Slack, I'm not sure what the right fix would be:

1. Create a new session once when a new connection is made.
2. Create a new session only when data is stored and don't start the underlying ext-session unless really needed (when data needs to be persisted).

Personally I prefer option 2: This way if someone make requests that don't need session data no sessions are created and no storage is used.

**Comment by alextech** [comment]
"This way if someone make requests that don't need session data no sessions
are created."

I think this is best compromise. I also did not expect session to
automatically always be there. Then, once I realize it did, I thought it
would work same as php session

сб, 30 июн. 2018 г., 13:15 Geert Eltink <notifications@github.com>:

**Comment by alextech** [comment]
P. S. But not only when data needs persisted. When explicitly requested to be started in general. Start when absolutely requested, for example in case of authentication, only when identity is actually confirmed. But once requested, IMO even if no data, that is still strong enough signal that it is a session that needs to be held on it.

**Comment by Ocramius** [comment]
In `psr7-sessions/storageless`, we solved this by using a lazy session container: https://github.com/psr7-sessions/storageless/blob/57dcf3de63675a3207f53d68c08b9be1ab2d2cbc/src/Storageless/Http/SessionMiddleware.php#L169-L171

**Comment by geerteltink** [comment]
zend-expressive-session is based on PSR-7 session and also uses a lazy session container. That's why it shouldn't start PHP sessions and create cookies unless there is a reason to.
