### ISSUE TITLE
Not supporting domain, secure neither cookie http only flags

### ISSUE THREAD

**Issue by smalot** [zendframework/zend-expressive-session-ext#30]
When using `php.ini` with such values:

```ini
session.cookie_domain = 'test.local'
session.cookie_httponly = 1
session.cookie_secure = 1
```

In such case, set-cookie should contain `Domain`, `Secure` and `HttpOnly`:

```
Set-Cookie: PHPSESSID=g6WMHd[...]fcZ; Path=/; Domain=test.local; Secure; HttpOnly
```

**Comment by weierophinney** [comment]
Could you send a pull request with the requested change, please?

**Comment by harikt** [comment]
@weierophinney I noticed @smalot send PR to his own branch https://github.com/smalot/zend-expressive-session-ext/pull/2 . May be you could just pull and merge ?

**Comment by weierophinney** [comment]
I've created #31, using the commits from smalot/zend-expressive-session-ext#2.
