### ISSUE TITLE
new empty session file created for every request with unused session

### ISSUE THREAD

**Issue by pine3ree** [zendframework/zend-expressive-session-ext#33]
The issue seems to be caused by this line: https://github.com/zendframework/zend-expressive-session-ext/blob/master/src/PhpSessionPersistence.php#L118

`persistSession` use the (lazy) session object, causing it to create a proxied session instance via `initializeSessionFromRequest` (see `LazySession::getProxiedSession()`), which in turn calls `session_start(new ID or cookie ID)`. A session with a new ID reflect on a new session file being written to.

If the session (data) has not changed, line 118 will return a response without sending the session cookie, so in the next request we will have a new session ID and therefore a new session file.

###### STEPS TO REPRODUCE THE ISSUE
just install zend-expressive-sessin-ext and add the session middleware to the application middleware queue.... Refresh a few times your app homepage and check the session files storage directory.
_Note_: make sure you are not using the session and empty your browser cookies for this test. If you have a leftover PHPSESSID cookie for, say, localhost:8080, that cookie value will be used instead for the session file. I discovered this issue when initializing a new project.

**Comment by pine3ree** [comment]
###### UPDATE
maybe the issue is not exactly in line 118.
The default php-ext behaviour is to set a session cookie when is not present in the request, once session_start is called and independently of session data changes. Tested with:
```php
<?php

session_start([
    'use_cookies'      => true,
    'use_only_cookies' => true,
    'use_trans_sid'    => false,
    'cookie_httponly'  => true,
    'cookie_lifetime'  => 0,
    'cookie_path'      => '/',
    'cache_limiter'    => '',
]);

$_SESSION['request_time_float'] = $_SERVER['REQUEST_TIME_FLOAT'];

header('content-type: application/json; charset=utf-8');
echo json_encode($_SESSION, JSON_PRETTY_PRINT);
```
and browser dev-tools.
php-ext will start a session using the session id provided by the request, or will generate a new id and send it back as a response cookie once. If you change the cookie session id (via EditThisCookie for example), that new id will be used to create a new file.

We want to mimic this behaviour (but inject the response cookie header ourself), so if the request session cookie is not set we must generate a new one and send it back. In the current implementation we generate a new id in initializeSessionFromRequest and save the request id in the session instance even if empty. In persistSession we should check if the session instance id is empty and use the session_id() (the generated one, used in session_start()) for the response cookie. (Or we should just memoize it in a property. In async php environments the persistence instance is shared but the setting of such property would be made on every request and read before another request write and read again, am i right?)

**Comment by pine3ree** [comment]
##### UPDATE
I am testing successfully the following changes:
```php
    //...
    private $requestSessionId;
    //...
    public function initializeSessionFromRequest(ServerRequestInterface $request) : SessionInterface
    {
        //...
        $this->requestSessionId = $this->getSessionIdFromRequest($request);
        $id = $this->requestSessionId ?: $this->generateSessionId();
        $this->startSession($id);

        return new Session($_SESSION, $id); // (*) USE THE REAL ID (from request or newly generated)
    }

    public function persistSession(SessionInterface $session, ResponseInterface $response) : ResponseInterface
    {
        // (*) Regenerate if the session is marked as regenerated
        if ($session->isRegenerated()) {
            $id = $this->regenerateSession(); // (*) this is a new non-empty session ID
        } else {
            $id = $session->getId(); // (*) this is the current non-empty session ID
        }

        $_SESSION = $session->toArray();
        session_write_close();

        // If the request session id is identical to the current session id
        // there's no reason to provide a cookie back to the user.
        if ($this->requestSessionId === $id) {
            return $response;
        }
        //....
```

**Comment by Ocramius** [comment]
Could you attempt to isolate the problem into a unit/integration test,
please?

**Comment by pine3ree** [comment]
@Ocramius 
Could a test like this be OK? 
I start with a cookie-less request and then "send" more requests with session-cookie taken from the response, if any. Then I check that only 1 session file is created.

kind regards

```php
//...
    public function testNewSessionFilesAreNotCreatedForCookielessRequest()
    {
        $session_name = 'TESTSESSID';
        $session_save_path = __DIR__ . "/sess";

        $ini = $this->applyCustomSessionOptions([
            'name'      => $session_name,
            'save_path' => $session_save_path,
        ]);

        // create a temp session save path
        if (!is_dir($session_save_path)) {
            mkdir($session_save_path);
        }

        // remove old session test files if any
        $files = glob("{$session_save_path}/sess_*");
        if ($files) {
            foreach ($files as $file) {
                unlink($file);
            }
        }

        $persistence = new PhpSessionPersistence();

        // initial sessioncookie-less request
        $request = new ServerRequest();

        for ($i = 0; $i < 3; $i += 1) {
            $session  = $persistence->initializeSessionFromRequest($request);
            $response = $persistence->persistSession($session, new Response());

            // new request: start w/o session cookie
            $request = new ServerRequest();

            // Add the latest response session cookie value to the new request, if any
            $setCookies = SetCookies::fromResponse($response);
            if ($setCookies->has($session_name)) {
                $setCookie = $setCookies->get($session_name);
            }
            if (isset($setCookie)) {
                $cookie = new Cookie($session_name, $setCookie->getValue());
                $request = FigRequestCookies::set($request, $cookie);
            }
        }

        $files = glob("{$session_save_path}/sess_*");

        $this->assertTrue(count($files) === 1);

        $this->restoreOriginalSessionIniSettings($ini);
    }
//...

**Comment by pine3ree** [comment]
To summarize, once the session middleware is registered a php-session is always created, the following calls are made (pseudo code):

$persistence->persistSession($lazy)
calls => $lazySession->getId()
calls => $lazySession->getProxiedSession()
calls => $persistence->initializeSessionFromRequest($request)
calls => $persistence->startSession($id)
calls => session_start()

session_start() is called on every request, but if a session cookie was not present in the request ($sessionId is empty, stored into $session->id) and data was not written to the session, Set-Cookie is not added to the response headers and the next request will not have a session cookie either, while a new php-session-id and session-file are created.

php-session behaviour is to send a Set-Cookie when: php-session is started and the session id differs from the one in the request request. 

(and after a successful session_start cache headers are always sent as well if cache_limiter is not empty)

**Comment by Ocramius** [comment]
Yes, a test that makes sure the global environment is reset is good enough 👌

**Comment by pine3ree** [comment]
Hello @weierophinney @Ocramius, @xtreamwayz.

I made some tests with standard php ext/sessions and i believe this package is behaving a little differently. Please pardon me (if) I am stating obvious facts.

Let's assume we are dealing with the common default case of having the same (whichever) session name (non need to change that unless you want to kick someone out....)

I found that:

-  A session cookie is added to the response only if
    - `session_start()` is called
    - AND
    - the last `session_id()` value differs from the (same name) session cookie value of the request (could be empty). The last session id could be different due to reopening a new session with a different id or regenerating the session. This also contradicts this comment [L114](https://github.com/zendframework/zend-expressive-session-ext/blob/master/src/PhpSessionPersistence.php#L114). (about that, I also believe that the session instance id should at any time match session_id() to avoid confusion)

- This happens independently of data read/written to the session file. A response session cookie just need to be set once per session id, it's the browser that (obviously) always send back that last id with the request)

- Changing the cookie_lifetime option on session_start() will not trigger a new Set-Cookie with different expiry date (*)

- Once session_start is called at least once, the cache headers are always sent if cache_limiter is not empty

(may be related https://github.com/zendframework/zend-expressive-session-ext/issues/23)

Do we wish to replicate this exact behaviour? 

IMHO i believe we should stay as close as possible. (*)The one difference that I can see if when we call `persistFor()`. In this case we obviously must send a cookie back with the new expiry time for the session cookie.

kind regards to everyone

**Comment by batumibiz** [comment]
I confirm, the problem is again present. Look here: [#1](https://github.com/zendframework/zend-expressive-session-ext/pull/1)  
I sent PR with correction more than a year ago.

**Comment by weierophinney** [comment]
@batumibiz Your PR was merged. If behavior it was fixing has come back, it means that we're missing tests covering this specific behavior. Perhaps you and @pine3ree could collaborate on writing tests and correcting the problem?

**Comment by batumibiz** [comment]
I did not mean a test, but an existing problem.
I have the same problem again on a live application as in #1
Tomorrow I'll compile a demo application again with a demonstration of the error and send the link.

**Comment by pine3ree** [comment]
fixed by https://github.com/zendframework/zend-expressive-session-ext/pull/36
